Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y python3-pip
  sudo apt install -y python-psycopg2
  SHELL
end
